In [36]:
#!pip3 install rich
#!pip3 install pandas
#!pip3 install uuid
#!pip3 install dataclasses
#!pip3 install typing
#!pip3 install json
#!pip3 install pathlib

Codi a netejar una miqueta

In [37]:
from participant import load_participants
from rich import print
import pandas as pd

data_path = "data/datathon_participants.json"
participants = load_participants(data_path)

df = pd.read_json(data_path)
df.to_csv("data/datathon_participants_csv.csv", index=False)

## Data PREPROCESSING

Innecessary

In [38]:
df.drop(['name', 'email', 'shirt_size', 'dietary_restrictions'], axis=1, inplace=True)
df.head()

,id,age,year_of_study,university,interests,preferred_role,experience_level,hackathons_done,objective,introduction,technical_project,future_excitement,fun_fact,preferred_languages,friend_registration,preferred_team_size,availability,programming_skills,interest_in_challenges
0,2ebad15c-c0ef-4c04-ba98-c5d98403a90c,21,4th year,Universitat Internacional de Catalunya (UIC),"[Fintech, Blockchain, Cybersecurity, Productiv...",Design,Intermediate,2,I'm super stoked to be participating in this d...,"Hi there! I'm Sara, and I'm super excited to b...",One project that really got me excited was bui...,"The future is so exciting! As I look ahead, I'...","Hey there! When I'm not coding, I love to belt...","[English, Catalan]",[],4,"{'Saturday morning': True, 'Saturday afternoon...","{'Data Visualization': 2, 'Flask': 4, 'React N...","[Mango Challenge, Restb.ai Challenge, AED Chal..."
1,a00428a2-14a2-4fb1-838a-22394778ec88,20,3rd year,Universitat Pompeu Fabra (UPF),"[Productivity, Enterprise, DevOps, Health, Rob...",Analysis,Intermediate,5,"For me, this datathon is all about leveling up...","Hey everyone! I'm Aurora, a 20-year-old studen...",I loved working on a productivity workflow opt...,"As I imagine my future, I'm thrilled to think ...","Hey there! When I'm not coding away, I love ex...",[English],[],3,"{'Saturday morning': True, 'Saturday afternoon...","{'React': 4, 'PostgreSQL': 5, 'Figma': 7, 'SQL...","[AED Challenge, Mango Challenge, Restb.ai Chal..."
2,ab4b5790-0e6b-43db-bbaa-8670554f0cc8,21,3rd year,Universidad de Sevilla,"[Lifehacks, Health, Cybersecurity, Communicati...",Analysis,Intermediate,2,"Hey! I'm Anaïs, and I'm all about growth and l...","Hey there! I'm Anaïs, a third-year student wit...","Oh, I just loved working on a project where I ...",I'm genuinely excited to work on developing AI...,"Hey! When I'm not coding, you can catch me sin...","[English, Spanish, French, German, Italian]",[],4,"{'Saturday morning': True, 'Saturday afternoon...","{'PostgreSQL': 4, 'TensorFlow': 5, 'Computer V...","[Restb.ai Challenge, Mango Challenge, AED Chal..."
3,cda2fafe-4b1e-4581-9fe0-1fb6d3e79aa3,21,3rd year,Universitat Internacional de Catalunya (UIC),"[Mobile, Cybersecurity, Quantum, E-commerce/Re...",Design,Intermediate,2,I'm all about leveling up my skills at this da...,"Hey! I'm Luna, a third-year student with a pas...",I once built a blockchain-based music sharing ...,I'm really stoked to dive into the realm of qu...,Who would've thought a programming newbie like...,"[English, Catalan]","[13a8194a-79a9-4004-8711-e6d89efa0014, 2a4877f...",4,"{'Saturday morning': True, 'Saturday afternoon...","{'IoT': 4, 'HTML/CSS': 6, 'MongoDB': 5, 'Block...","[Restb.ai Challenge, AED Challenge, Mango Chal..."
4,624f4677-d31a-4ecf-a7de-5df7392f9579,20,3rd year,Universitat Politècnica de Catalunya (UPC),"[Quantum, Fintech, Blockchain, DevOps, Lifehac...",Design,Intermediate,2,I'm coming to this datathon to put my skills t...,"Hey there! I'm Evelyn Winters, a third-year st...",One of my favorite projects was a computer vis...,I'm thrilled to see my passion for quantum com...,I'm a closet artist! When I'm not geeking out ...,[English],[],4,"{'Saturday morning': True, 'Saturday afternoon...","{'iOS Development': 2, 'Flask': 6, 'TensorFlow...","[Restb.ai Challenge, AED Challenge, Mango Chal..."

Year_of_study

In [39]:
mapping = {
    '1st year': 1,
    '2nd year': 2,
    '3rd year': 3,
    '4th year': 4,
    'master': 5,
    'PhD': 6
}

df['year_of_study'] = df['year_of_study'].map(mapping)
df.head()

,id,age,year_of_study,university,interests,preferred_role,experience_level,hackathons_done,objective,introduction,technical_project,future_excitement,fun_fact,preferred_languages,friend_registration,preferred_team_size,availability,programming_skills,interest_in_challenges
0,2ebad15c-c0ef-4c04-ba98-c5d98403a90c,21,4.0,Universitat Internacional de Catalunya (UIC),"[Fintech, Blockchain, Cybersecurity, Productiv...",Design,Intermediate,2,I'm super stoked to be participating in this d...,"Hi there! I'm Sara, and I'm super excited to b...",One project that really got me excited was bui...,"The future is so exciting! As I look ahead, I'...","Hey there! When I'm not coding, I love to belt...","[English, Catalan]",[],4,"{'Saturday morning': True, 'Saturday afternoon...","{'Data Visualization': 2, 'Flask': 4, 'React N...","[Mango Challenge, Restb.ai Challenge, AED Chal..."
1,a00428a2-14a2-4fb1-838a-22394778ec88,20,3.0,Universitat Pompeu Fabra (UPF),"[Productivity, Enterprise, DevOps, Health, Rob...",Analysis,Intermediate,5,"For me, this datathon is all about leveling up...","Hey everyone! I'm Aurora, a 20-year-old studen...",I loved working on a productivity workflow opt...,"As I imagine my future, I'm thrilled to think ...","Hey there! When I'm not coding away, I love ex...",[English],[],3,"{'Saturday morning': True, 'Saturday afternoon...","{'React': 4, 'PostgreSQL': 5, 'Figma': 7, 'SQL...","[AED Challenge, Mango Challenge, Restb.ai Chal..."
2,ab4b5790-0e6b-43db-bbaa-8670554f0cc8,21,3.0,Universidad de Sevilla,"[Lifehacks, Health, Cybersecurity, Communicati...",Analysis,Intermediate,2,"Hey! I'm Anaïs, and I'm all about growth and l...","Hey there! I'm Anaïs, a third-year student wit...","Oh, I just loved working on a project where I ...",I'm genuinely excited to work on developing AI...,"Hey! When I'm not coding, you can catch me sin...","[English, Spanish, French, German, Italian]",[],4,"{'Saturday morning': True, 'Saturday afternoon...","{'PostgreSQL': 4, 'TensorFlow': 5, 'Computer V...","[Restb.ai Challenge, Mango Challenge, AED Chal..."
3,cda2fafe-4b1e-4581-9fe0-1fb6d3e79aa3,21,3.0,Universitat Internacional de Catalunya (UIC),"[Mobile, Cybersecurity, Quantum, E-commerce/Re...",Design,Intermediate,2,I'm all about leveling up my skills at this da...,"Hey! I'm Luna, a third-year student with a pas...",I once built a blockchain-based music sharing ...,I'm really stoked to dive into the realm of qu...,Who would've thought a programming newbie like...,"[English, Catalan]","[13a8194a-79a9-4004-8711-e6d89efa0014, 2a4877f...",4,"{'Saturday morning': True, 'Saturday afternoon...","{'IoT': 4, 'HTML/CSS': 6, 'MongoDB': 5, 'Block...","[Restb.ai Challenge, AED Challenge, Mango Chal..."
4,624f4677-d31a-4ecf-a7de-5df7392f9579,20,3.0,Universitat Politècnica de Catalunya (UPC),"[Quantum, Fintech, Blockchain, DevOps, Lifehac...",Design,Intermediate,2,I'm coming to this datathon to put my skills t...,"Hey there! I'm Evelyn Winters, a third-year st...",One of my favorite projects was a computer vis...,I'm thrilled to see my passion for quantum com...,I'm a closet artist! When I'm not geeking out ...,[English],[],4,"{'Saturday morning': True, 'Saturday afternoon...","{'iOS Development': 2, 'Flask': 6, 'TensorFlow...","[Restb.ai Challenge, AED Challenge, Mango Chal..."

Interests

In [40]:
all_interests = df['interests'].explode().unique()

for value in all_interests:
    df[f'has_{value}'] = df['interests'].apply(lambda x: 1 if value in x else 0)


df['interests'] = df[[f'has_{value}' for value in all_interests]].values.tolist()

df = df.drop(columns=[f'has_{value}' for value in all_interests])

df.head()

,id,age,year_of_study,university,interests,preferred_role,experience_level,hackathons_done,objective,introduction,technical_project,future_excitement,fun_fact,preferred_languages,friend_registration,preferred_team_size,availability,programming_skills,interest_in_challenges
0,2ebad15c-c0ef-4c04-ba98-c5d98403a90c,21,4.0,Universitat Internacional de Catalunya (UIC),"[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Design,Intermediate,2,I'm super stoked to be participating in this d...,"Hi there! I'm Sara, and I'm super excited to b...",One project that really got me excited was bui...,"The future is so exciting! As I look ahead, I'...","Hey there! When I'm not coding, I love to belt...","[English, Catalan]",[],4,"{'Saturday morning': True, 'Saturday afternoon...","{'Data Visualization': 2, 'Flask': 4, 'React N...","[Mango Challenge, Restb.ai Challenge, AED Chal..."
1,a00428a2-14a2-4fb1-838a-22394778ec88,20,3.0,Universitat Pompeu Fabra (UPF),"[0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, ...",Analysis,Intermediate,5,"For me, this datathon is all about leveling up...","Hey everyone! I'm Aurora, a 20-year-old studen...",I loved working on a productivity workflow opt...,"As I imagine my future, I'm thrilled to think ...","Hey there! When I'm not coding away, I love ex...",[English],[],3,"{'Saturday morning': True, 'Saturday afternoon...","{'React': 4, 'PostgreSQL': 5, 'Figma': 7, 'SQL...","[AED Challenge, Mango Challenge, Restb.ai Chal..."
2,ab4b5790-0e6b-43db-bbaa-8670554f0cc8,21,3.0,Universidad de Sevilla,"[0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, ...",Analysis,Intermediate,2,"Hey! I'm Anaïs, and I'm all about growth and l...","Hey there! I'm Anaïs, a third-year student wit...","Oh, I just loved working on a project where I ...",I'm genuinely excited to work on developing AI...,"Hey! When I'm not coding, you can catch me sin...","[English, Spanish, French, German, Italian]",[],4,"{'Saturday morning': True, 'Saturday afternoon...","{'PostgreSQL': 4, 'TensorFlow': 5, 'Computer V...","[Restb.ai Challenge, Mango Challenge, AED Chal..."
3,cda2fafe-4b1e-4581-9fe0-1fb6d3e79aa3,21,3.0,Universitat Internacional de Catalunya (UIC),"[0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, ...",Design,Intermediate,2,I'm all about leveling up my skills at this da...,"Hey! I'm Luna, a third-year student with a pas...",I once built a blockchain-based music sharing ...,I'm really stoked to dive into the realm of qu...,Who would've thought a programming newbie like...,"[English, Catalan]","[13a8194a-79a9-4004-8711-e6d89efa0014, 2a4877f...",4,"{'Saturday morning': True, 'Saturday afternoon...","{'IoT': 4, 'HTML/CSS': 6, 'MongoDB': 5, 'Block...","[Restb.ai Challenge, AED Challenge, Mango Chal..."
4,624f4677-d31a-4ecf-a7de-5df7392f9579,20,3.0,Universitat Politècnica de Catalunya (UPC),"[1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, ...",Design,Intermediate,2,I'm coming to this datathon to put my skills t...,"Hey there! I'm Evelyn Winters, a third-year st...",One of my favorite projects was a computer vis...,I'm thrilled to see my passion for quantum com...,I'm a closet artist! When I'm not geeking out ...,[English],[],4,"{'Saturday morning': True, 'Saturday afternoon...","{'iOS Development': 2, 'Flask': 6, 'TensorFlow...","[Restb.ai Challenge, AED Challenge, Mango Chal..."

preferred_role

In [41]:
df['preferred_role'].unique()

array(['Design', 'Analysis', 'Development', "Don't know", 'Visualization',
       "Don't care"], dtype=object)

experience_level

In [42]:
df['experience_level'].unique()

array(['Intermediate', 'Beginner', 'Advanced'], dtype=object)

In [43]:
import numpy as np

mapping = {
    'Advanced': 10,
    'Intermediate': 4, 
    'Beginner': 1
}

df['experience_level'] = df['experience_level'].map(mapping)

df['experience'] = df['experience_level'] * np.log(1 + df['hackathons_done'])
df.drop(['experience_level', 'hackathons_done'], axis=1, inplace=True)

df.head()

,id,age,year_of_study,university,interests,preferred_role,objective,introduction,technical_project,future_excitement,fun_fact,preferred_languages,friend_registration,preferred_team_size,availability,programming_skills,interest_in_challenges,experience
0,2ebad15c-c0ef-4c04-ba98-c5d98403a90c,21,4.0,Universitat Internacional de Catalunya (UIC),"[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Design,I'm super stoked to be participating in this d...,"Hi there! I'm Sara, and I'm super excited to b...",One project that really got me excited was bui...,"The future is so exciting! As I look ahead, I'...","Hey there! When I'm not coding, I love to belt...","[English, Catalan]",[],4,"{'Saturday morning': True, 'Saturday afternoon...","{'Data Visualization': 2, 'Flask': 4, 'React N...","[Mango Challenge, Restb.ai Challenge, AED Chal...",4.394449
1,a00428a2-14a2-4fb1-838a-22394778ec88,20,3.0,Universitat Pompeu Fabra (UPF),"[0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, ...",Analysis,"For me, this datathon is all about leveling up...","Hey everyone! I'm Aurora, a 20-year-old studen...",I loved working on a productivity workflow opt...,"As I imagine my future, I'm thrilled to think ...","Hey there! When I'm not coding away, I love ex...",[English],[],3,"{'Saturday morning': True, 'Saturday afternoon...","{'React': 4, 'PostgreSQL': 5, 'Figma': 7, 'SQL...","[AED Challenge, Mango Challenge, Restb.ai Chal...",7.167038
2,ab4b5790-0e6b-43db-bbaa-8670554f0cc8,21,3.0,Universidad de Sevilla,"[0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, ...",Analysis,"Hey! I'm Anaïs, and I'm all about growth and l...","Hey there! I'm Anaïs, a third-year student wit...","Oh, I just loved working on a project where I ...",I'm genuinely excited to work on developing AI...,"Hey! When I'm not coding, you can catch me sin...","[English, Spanish, French, German, Italian]",[],4,"{'Saturday morning': True, 'Saturday afternoon...","{'PostgreSQL': 4, 'TensorFlow': 5, 'Computer V...","[Restb.ai Challenge, Mango Challenge, AED Chal...",4.394449
3,cda2fafe-4b1e-4581-9fe0-1fb6d3e79aa3,21,3.0,Universitat Internacional de Catalunya (UIC),"[0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, ...",Design,I'm all about leveling up my skills at this da...,"Hey! I'm Luna, a third-year student with a pas...",I once built a blockchain-based music sharing ...,I'm really stoked to dive into the realm of qu...,Who would've thought a programming newbie like...,"[English, Catalan]","[13a8194a-79a9-4004-8711-e6d89efa0014, 2a4877f...",4,"{'Saturday morning': True, 'Saturday afternoon...","{'IoT': 4, 'HTML/CSS': 6, 'MongoDB': 5, 'Block...","[Restb.ai Challenge, AED Challenge, Mango Chal...",4.394449
4,624f4677-d31a-4ecf-a7de-5df7392f9579,20,3.0,Universitat Politècnica de Catalunya (UPC),"[1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, ...",Design,I'm coming to this datathon to put my skills t...,"Hey there! I'm Evelyn Winters, a third-year st...",One of my favorite projects was a computer vis...,I'm thrilled to see my passion for quantum com...,I'm a closet artist! When I'm not geeking out ...,[English],[],4,"{'Saturday morning': True, 'Saturday afternoon...","{'iOS Development': 2, 'Flask': 6, 'TensorFlow...","[Restb.ai Challenge, AED Challenge, Mango Chal...",4.394449

Sort lenguages list

In [44]:
all_interests = df['preferred_languages'].explode().unique()
all_interests

array(['English', 'Catalan', 'Spanish', 'French', 'German', 'Italian',
       'Portuguese', nan], dtype=object)

In [45]:
def sort_languages(languages):
    preference_order = {
        'Catalan': 0,
        'Spanish': 1,
        'English': 2
    }
    

    def sort_key(language):
        return preference_order.get(language, 3)
    
    return sorted(languages, key=sort_key)

df['languages_ordered'] = df['preferred_languages'].apply(sort_languages)
df.drop('preferred_languages', axis=1, inplace=True)

df.head()

,id,age,year_of_study,university,interests,preferred_role,objective,introduction,technical_project,future_excitement,fun_fact,friend_registration,preferred_team_size,availability,programming_skills,interest_in_challenges,experience,languages_ordered
0,2ebad15c-c0ef-4c04-ba98-c5d98403a90c,21,4.0,Universitat Internacional de Catalunya (UIC),"[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Design,I'm super stoked to be participating in this d...,"Hi there! I'm Sara, and I'm super excited to b...",One project that really got me excited was bui...,"The future is so exciting! As I look ahead, I'...","Hey there! When I'm not coding, I love to belt...",[],4,"{'Saturday morning': True, 'Saturday afternoon...","{'Data Visualization': 2, 'Flask': 4, 'React N...","[Mango Challenge, Restb.ai Challenge, AED Chal...",4.394449,"[Catalan, English]"
1,a00428a2-14a2-4fb1-838a-22394778ec88,20,3.0,Universitat Pompeu Fabra (UPF),"[0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, ...",Analysis,"For me, this datathon is all about leveling up...","Hey everyone! I'm Aurora, a 20-year-old studen...",I loved working on a productivity workflow opt...,"As I imagine my future, I'm thrilled to think ...","Hey there! When I'm not coding away, I love ex...",[],3,"{'Saturday morning': True, 'Saturday afternoon...","{'React': 4, 'PostgreSQL': 5, 'Figma': 7, 'SQL...","[AED Challenge, Mango Challenge, Restb.ai Chal...",7.167038,[English]
2,ab4b5790-0e6b-43db-bbaa-8670554f0cc8,21,3.0,Universidad de Sevilla,"[0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, ...",Analysis,"Hey! I'm Anaïs, and I'm all about growth and l...","Hey there! I'm Anaïs, a third-year student wit...","Oh, I just loved working on a project where I ...",I'm genuinely excited to work on developing AI...,"Hey! When I'm not coding, you can catch me sin...",[],4,"{'Saturday morning': True, 'Saturday afternoon...","{'PostgreSQL': 4, 'TensorFlow': 5, 'Computer V...","[Restb.ai Challenge, Mango Challenge, AED Chal...",4.394449,"[Spanish, English, French, German, Italian]"
3,cda2fafe-4b1e-4581-9fe0-1fb6d3e79aa3,21,3.0,Universitat Internacional de Catalunya (UIC),"[0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, ...",Design,I'm all about leveling up my skills at this da...,"Hey! I'm Luna, a third-year student with a pas...",I once built a blockchain-based music sharing ...,I'm really stoked to dive into the realm of qu...,Who would've thought a programming newbie like...,"[13a8194a-79a9-4004-8711-e6d89efa0014, 2a4877f...",4,"{'Saturday morning': True, 'Saturday afternoon...","{'IoT': 4, 'HTML/CSS': 6, 'MongoDB': 5, 'Block...","[Restb.ai Challenge, AED Challenge, Mango Chal...",4.394449,"[Catalan, English]"
4,624f4677-d31a-4ecf-a7de-5df7392f9579,20,3.0,Universitat Politècnica de Catalunya (UPC),"[1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, ...",Design,I'm coming to this datathon to put my skills t...,"Hey there! I'm Evelyn Winters, a third-year st...",One of my favorite projects was a computer vis...,I'm thrilled to see my passion for quantum com...,I'm a closet artist! When I'm not geeking out ...,[],4,"{'Saturday morning': True, 'Saturday afternoon...","{'iOS Development': 2, 'Flask': 6, 'TensorFlow...","[Restb.ai Challenge, AED Challenge, Mango Chal...",4.394449,[English]

madurity

In [46]:
weight_level = 1
weight_age = 0.2

df['maturity'] = (df['year_of_study'] * weight_level) + ((df['age'] - 18) * weight_age)
df.drop(['age', 'year_of_study'], axis=1, inplace=True)
df.head()

,id,university,interests,preferred_role,objective,introduction,technical_project,future_excitement,fun_fact,friend_registration,preferred_team_size,availability,programming_skills,interest_in_challenges,experience,languages_ordered,maturity
0,2ebad15c-c0ef-4c04-ba98-c5d98403a90c,Universitat Internacional de Catalunya (UIC),"[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Design,I'm super stoked to be participating in this d...,"Hi there! I'm Sara, and I'm super excited to b...",One project that really got me excited was bui...,"The future is so exciting! As I look ahead, I'...","Hey there! When I'm not coding, I love to belt...",[],4,"{'Saturday morning': True, 'Saturday afternoon...","{'Data Visualization': 2, 'Flask': 4, 'React N...","[Mango Challenge, Restb.ai Challenge, AED Chal...",4.394449,"[Catalan, English]",4.6
1,a00428a2-14a2-4fb1-838a-22394778ec88,Universitat Pompeu Fabra (UPF),"[0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, ...",Analysis,"For me, this datathon is all about leveling up...","Hey everyone! I'm Aurora, a 20-year-old studen...",I loved working on a productivity workflow opt...,"As I imagine my future, I'm thrilled to think ...","Hey there! When I'm not coding away, I love ex...",[],3,"{'Saturday morning': True, 'Saturday afternoon...","{'React': 4, 'PostgreSQL': 5, 'Figma': 7, 'SQL...","[AED Challenge, Mango Challenge, Restb.ai Chal...",7.167038,[English],3.4
2,ab4b5790-0e6b-43db-bbaa-8670554f0cc8,Universidad de Sevilla,"[0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, ...",Analysis,"Hey! I'm Anaïs, and I'm all about growth and l...","Hey there! I'm Anaïs, a third-year student wit...","Oh, I just loved working on a project where I ...",I'm genuinely excited to work on developing AI...,"Hey! When I'm not coding, you can catch me sin...",[],4,"{'Saturday morning': True, 'Saturday afternoon...","{'PostgreSQL': 4, 'TensorFlow': 5, 'Computer V...","[Restb.ai Challenge, Mango Challenge, AED Chal...",4.394449,"[Spanish, English, French, German, Italian]",3.6
3,cda2fafe-4b1e-4581-9fe0-1fb6d3e79aa3,Universitat Internacional de Catalunya (UIC),"[0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, ...",Design,I'm all about leveling up my skills at this da...,"Hey! I'm Luna, a third-year student with a pas...",I once built a blockchain-based music sharing ...,I'm really stoked to dive into the realm of qu...,Who would've thought a programming newbie like...,"[13a8194a-79a9-4004-8711-e6d89efa0014, 2a4877f...",4,"{'Saturday morning': True, 'Saturday afternoon...","{'IoT': 4, 'HTML/CSS': 6, 'MongoDB': 5, 'Block...","[Restb.ai Challenge, AED Challenge, Mango Chal...",4.394449,"[Catalan, English]",3.6
4,624f4677-d31a-4ecf-a7de-5df7392f9579,Universitat Politècnica de Catalunya (UPC),"[1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, ...",Design,I'm coming to this datathon to put my skills t...,"Hey there! I'm Evelyn Winters, a third-year st...",One of my favorite projects was a computer vis...,I'm thrilled to see my passion for quantum com...,I'm a closet artist! When I'm not geeking out ...,[],4,"{'Saturday morning': True, 'Saturday afternoon...","{'iOS Development': 2, 'Flask': 6, 'TensorFlow...","[Restb.ai Challenge, AED Challenge, Mango Chal...",4.394449,[English],3.4

availability

In [47]:
time_slots_order = ['Saturday morning', 'Saturday afternoon', 'Saturday night', 
                    'Sunday morning', 'Sunday afternoon']

# Funció per convertir el diccionari de franges horàries en un vector de 0s i 1s
def time_slots_to_vector(time_slots):
    return [1 if time_slots.get(slot, False) else 0 for slot in time_slots_order]

# Aplicar la funció a cada fila de la columna 'time_slots' i guardar el resultat en una nova columna
df['availability'] = df['availability'].apply(time_slots_to_vector)

df.head()

,id,university,interests,preferred_role,objective,introduction,technical_project,future_excitement,fun_fact,friend_registration,preferred_team_size,availability,programming_skills,interest_in_challenges,experience,languages_ordered,maturity
0,2ebad15c-c0ef-4c04-ba98-c5d98403a90c,Universitat Internacional de Catalunya (UIC),"[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Design,I'm super stoked to be participating in this d...,"Hi there! I'm Sara, and I'm super excited to b...",One project that really got me excited was bui...,"The future is so exciting! As I look ahead, I'...","Hey there! When I'm not coding, I love to belt...",[],4,"[1, 1, 0, 1, 1]","{'Data Visualization': 2, 'Flask': 4, 'React N...","[Mango Challenge, Restb.ai Challenge, AED Chal...",4.394449,"[Catalan, English]",4.6
1,a00428a2-14a2-4fb1-838a-22394778ec88,Universitat Pompeu Fabra (UPF),"[0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, ...",Analysis,"For me, this datathon is all about leveling up...","Hey everyone! I'm Aurora, a 20-year-old studen...",I loved working on a productivity workflow opt...,"As I imagine my future, I'm thrilled to think ...","Hey there! When I'm not coding away, I love ex...",[],3,"[1, 0, 1, 0, 1]","{'React': 4, 'PostgreSQL': 5, 'Figma': 7, 'SQL...","[AED Challenge, Mango Challenge, Restb.ai Chal...",7.167038,[English],3.4
2,ab4b5790-0e6b-43db-bbaa-8670554f0cc8,Universidad de Sevilla,"[0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, ...",Analysis,"Hey! I'm Anaïs, and I'm all about growth and l...","Hey there! I'm Anaïs, a third-year student wit...","Oh, I just loved working on a project where I ...",I'm genuinely excited to work on developing AI...,"Hey! When I'm not coding, you can catch me sin...",[],4,"[1, 1, 1, 1, 1]","{'PostgreSQL': 4, 'TensorFlow': 5, 'Computer V...","[Restb.ai Challenge, Mango Challenge, AED Chal...",4.394449,"[Spanish, English, French, German, Italian]",3.6
3,cda2fafe-4b1e-4581-9fe0-1fb6d3e79aa3,Universitat Internacional de Catalunya (UIC),"[0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, ...",Design,I'm all about leveling up my skills at this da...,"Hey! I'm Luna, a third-year student with a pas...",I once built a blockchain-based music sharing ...,I'm really stoked to dive into the realm of qu...,Who would've thought a programming newbie like...,"[13a8194a-79a9-4004-8711-e6d89efa0014, 2a4877f...",4,"[1, 1, 0, 1, 1]","{'IoT': 4, 'HTML/CSS': 6, 'MongoDB': 5, 'Block...","[Restb.ai Challenge, AED Challenge, Mango Chal...",4.394449,"[Catalan, English]",3.6
4,624f4677-d31a-4ecf-a7de-5df7392f9579,Universitat Politècnica de Catalunya (UPC),"[1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, ...",Design,I'm coming to this datathon to put my skills t...,"Hey there! I'm Evelyn Winters, a third-year st...",One of my favorite projects was a computer vis...,I'm thrilled to see my passion for quantum com...,I'm a closet artist! When I'm not geeking out ...,[],4,"[1, 1, 1, 1, 1]","{'iOS Development': 2, 'Flask': 6, 'TensorFlow...","[Restb.ai Challenge, AED Challenge, Mango Chal...",4.394449,[English],3.4